name: "swiftkube-model-ci"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Test
        run: swift test --enable-test-discovery
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["swift:5.9", "swift:5.10", "swift:6.0"]
    container: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Test
        run: swift test --enable-test-discovery
  iOS:
    name: Test iOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme SwiftkubeModel -destination "${{ matrix.destination }}" clean test | xcpretty
