name: "swiftkube-model-ci"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: set -o pipefail && swift build -v
    - name: Test
      run: set -o pipefail && swift test --enable-test-discovery
  iOS:
    name: Test iOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme SwiftkubeModel -destination "${{ matrix.destination }}" clean test | xcpretty
  linux:
    runs-on: ubuntu-latest
    container: swift:5.6
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v --enable-test-discovery
    - name: Test
      run: swift test --enable-test-discovery
